name: BOT CI

on: [pull_request, push]
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python3 -m pip3 install --upgrade pip
        pip3 install mypy
        pip3 install ruff

    - name: Run linters
      run: |
        ./moex_alerter_bot/linter.sh
    
    # - name: Run Tests
    #   run: |
    #     python manage.py test
