name: BOT CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install mypy
        pip install ruff

    - name: List dir
      run: ls -l

    - name: Ruff check
      run: ruff check --fix $(git ls-files '*.py')

    - name: Ruff format
      run: ruff format $(git ls-files '*.py')

    - name: Mypy
      run: mypy --ignore-missing-imports $(git ls-files '*.py')