name: BOT CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          mkdir -p /opt/git
          cd /opt/git
          git pull origin main
          git status