name: BOT CD

on: [push]

env:
  PROJECT_DIR: /opt/git/moex-alerter-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          echo "$PROJECT_DIR"
          if [ ! -d "$PROJECT_DIR"]; then
            mkdir -p /opt/git
            cd /opt/git
            git clone https://github.com/AChesnov/moex-alerter-bot.git
          fi
          cd $PROJECT_DIR
          ls -l
          git pull origin main
          git status